### ISSUE TITLE
prometheus software not correct 2.36.0 is in reality 2.15.2 

### ISSUE THREAD

**Issue by ErwinKlaus** [IBM/ibm-z-oss-hub#134]
**Image Name and Version**
prometheus 2.36.0

**Describe the bug**
After a docker pull of icr.io/ibmz/prometheus@sha256:cd15a12738595338e7fdf72780f60f2f61a3a11021dff7d0d5dedbbb8135f4a3 on a x86 linux system, a docker save of this image, a docker load of this image and starting this image it appears that I have an old prometheus version: 2.15.2

**To Reproduce**

- get the image: docker pull  icr.io/ibmz/prometheus@sha256:cd15a12738595338e7fdf72780f60f2f61a3a11021dff7d0d5dedbbb8135f4a3

- save the image: docker save -o something.tar icr.io/ibmz/prometheus@sha256:cd15a12738595338e7fdf72780f60f2f61a3a11021dff7d0d5dedbbb8135f4a3

- copy something.tar to the target system

- load the image on airgapped system: docker load -i something.tar 

- tag the image because it lost it's name: docker image tag e16ed7c83f27 prometheus:latest 

- start the container as decribed: docker run --name prometheus --network prometheus_network  -p 9090:9090 -d prometheus

- validate the version by going to: http://dnsname:9090/status, Build Information, Version 2.15.2

**Expected behavior**
I was expecting version 2.36.0 

**Screenshots**

**Additional context**
Because the target system is an airgapped system a pull, save, copy and load sequence is required
Maybe I'm doing something wrong, please advise.

**Comment by korpx-z** [comment]
I will look investigate this right now and update the issue momentarily with what I find.

**Comment by korpx-z** [comment]
I am seeing the same thing!
Thank you for pointing this out - and sorry you had to deal with it!

I'll work on replacing the prometheus stack now.

**Comment by korpx-z** [comment]
I have uploaded a new version of `icr.io/ibmz/prometheus:2.36.0` built with the appropriate source!

Let me know if you find any issues with your use of the image.. and please use our official index to locate the appropriate pull string (sha256). I'll close this issue for now, but if anything is wrong feel free to reopen.
