### ISSUE TITLE
OpenJDK 11 image is getting pretty dated

### ISSUE THREAD

**Issue by JoshWisniewski00** [IBM/ibm-z-oss-hub#137]
**Software Name**
OpenJDK 

**Software Version**
Updated version of Java 11.

**Notes**
The existing version was created 05-19-2022 and has a lot of vulnerabilities at this point.  https://ibm.github.io/ibm-z-oss-hub/containers/openjdk.html

**Comment by korpx-z** [comment]
We have uploaded fresh builds of all versions of openjdk *except* 14 - which will be delivered shortly as well.
`icr.io/ibmz/openjdk:11` is now vulnerability free.
Please reference the official index for the appropriate pull string (one that is including the sha256 value)

I'll close this issue for now, but feel free to reopen or create a new one if you have any issues!

**Comment by JoshWisniewski00** [comment]
Awesome.  thank you!
