### ISSUE TITLE
Image Request: 

### ISSUE THREAD

**Issue by JoshWisniewski00** [IBM/ibm-z-oss-hub#156]
**Software Name**
Grafana

**Software Version**
10.3.4

**Software Value**
Our security scan tools are mandating that we upgrade due to a vulnerability: https://www.tenable.com/plugins/nessus/192023

**Comment by korpx-z** [comment]
A new image (Grafana version 10.3.4) has been uploaded - please reference the official landing page for the appropriate pull string.
If there are any issues using the image please feel free to reopen this issue!

**Comment by JoshWisniewski00** [comment]
Thank you!

**Comment by v1gnesh** [comment]
@korpx-z Any chance you can add a build script for Grafana 11 to linux-on-ibm-z/scripts repo, and the an icr image for the same (here)?
