### ISSUE TITLE
Prometheus 2.54.0 error when starting

### ISSUE THREAD

**Issue by hem2023** [IBM/ibm-z-oss-hub#176]
**Image Name and Version**
icr.io/ibmz/prometheus:2.54.0

**Describe the bug**
When starting the image, I get an error. Looks like the entrypoint is not correct.

**To Reproduce**
Started with the following command:
docker run --name prometheus --restart always -d --network monitoring -v prometheus-data:/prometheus -p 9090:9090 -d icr.io/ibmz/prometheus:2.54.0

**Expected behavior**
Start of the container without this error

**Screenshots**

**Additional context**

**Comment by hem2023** [comment]
Screenshot
![prometheus](https://github.com/user-attachments/assets/fef6de22-8ba3-431a-988a-86bd03619ead)

**Comment by v1gnesh** [comment]
@hem2023 Apologies in advance for an unrelated comment - please try [VictoriaMetrics](https://victoriametrics.com/) instead. It is significantly more effective & efficient than Prometheues, while being a drop-in replacement.

**Comment by korpx-z** [comment]
@hem2023 thanks for lettings us know! As of this moment I am unable to recreate the failure.. I will continue to look into this though and will let you know if I can recreate the error you see. 
Are you still encountering the entrypoint error?

```
~/prometheus$ docker run --name prometheus --restart always -d -v prometheus-data:/prometheus -p 9090:9090 -d icr.io/ibmz/prometheus:2.54.0
ff14e7b5b040d6f5e4b601455afc60c0f92fe41c6e5d7da8ccdf59e64f25cff7
```
```
~/prometheus$ docker logs ff14e7b5b040d6f5e4b601455afc60c0f92fe41c6e5d7da8ccdf59e64f25cff7
ts=2024-09-19T20:05:49.204Z caller=main.go:601 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2024-09-19T20:05:49.204Z caller=main.go:645 level=info msg="Starting Prometheus Server" mode=server version="(version=2.54.0, branch=non-git, revision=non-git)"
ts=2024-09-19T20:05:49.204Z caller=main.go:650 level=info build_context="(go=go1.22.5, platform=linux/s390x, user=root@buildkitsandbox, date=20240822-18:27:18, tags=netgo,builtinassets,stringlabels)"
```
