### ISSUE TITLE
Image Request: MariaDB 11.4.2 or later

### ISSUE THREAD

**Issue by JoshWisniewski00** [IBM/ibm-z-oss-hub#187]
**MariaDB**

**11.4.2 or later**

**Software Value**
Provides ubiquitous open source relational DB.  The z/TPF runtime metrics collection sample analytics pipeline is used by various customers to monitor operational and business metrics from production systems.  Currently, all required open source containers (Grafana, OpenJDK, Python, etc) are installed from ICR but MariaDB.  Now that dockerhub is going to start charging to pull images and IBM is going to block access, we can no longer direct our customers to docker hub:  https://hub.docker.com/layers/library/mariadb/11.4.2/images/sha256-3af38083c53ea90d6bec2e69244c583cb7287759fc3d9cbaa60d79a3c7be1be8?context=explore As such, we need a viable container registry to provide MariaDB.  The ideal situation is for ICR to provide MariaDB such that all of our open-source container dependencies are coming from a trusted IBM provider.

**Comment by korpx-z** [comment]
I have built and uploaded version 11.6.1 of mariadb, please reference the official landing page for an appropriate pull string.
If you have any issues using this image please feel free to reopen this ticket or create a new one!

**Comment by JoshWisniewski00** [comment]
Awesome!  Thank you!
