### ISSUE TITLE
Onboarding Zowe to zICR

### ISSUE THREAD

**Issue by FlappiTomic** [IBM/ibm-z-oss-hub#31]
ZOWE components:

api-catalog:
zowe-docker-release.jfrog.io/ompzowe/api-catalog-services:2.0-ubuntu-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/api-catalog-services:2.0-ubuntu-linux-s390x
zowe-docker-release.jfrog.io/ompzowe/api-catalog-services:2.0-ubi-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/api-catalog-services:2.0-ubi-linux-s390x

app-server: (not final yet)
zowe-docker-snapshot.jfrog.io/ompzowe/app-server:2.0.0-ubi.v2-x-staging-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/app-server:2.0.0-ubi.v2-x-staging-linux-s390x
zowe-docker-snapshot.jfrog.io/ompzowe/app-server:2.0.0-ubuntu.v2-x-staging-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/app-server:2.0.0-ubuntu.v2-x-staging-linux-s390x

caching-services:
zowe-docker-release.jfrog.io/ompzowe/caching-service:2.0-ubi-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/caching-service:2.0-ubi-linux-s390x
zowe-docker-release.jfrog.io/ompzowe/caching-service:2.0-ubuntu-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/caching-service:2.0-ubuntu-linux-s390x

discovery-service:
zowe-docker-release.jfrog.io/ompzowe/discovery-service:2.0-ubi-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/discovery-service:2.0-ubi-linux-s390x
zowe-docker-release.jfrog.io/ompzowe/discovery-service:2.0-ubuntu-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/discovery-service:2.0-ubuntu-linux-s390x

gateway-service:
zowe-docker-release.jfrog.io/ompzowe/gateway-service:2.0-ubi-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/gateway-service:2.0-ubi-linux-s390x
zowe-docker-release.jfrog.io/ompzowe/gateway-service:2.0-ubuntu-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/gateway-service:2.0-ubuntu-linux-s390x

zowe-launch-scripts: (not final yet)
zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:2.0.0-ubi.v2-x-staging-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:2.0.0-ubi.v2-x-staging-linux-s390x
zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:2.0.0-ubuntu.v2-x-staging-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:2.0.0-ubuntu.v2-x-staging-linux-s390x

files-api: (not final yet)
zowe-docker-snapshot.jfrog.io/ompzowe/files-api:2.0.0-ubi.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/files-api:2.0.0-ubi.v2-x-master-linux-s390x
zowe-docker-snapshot.jfrog.io/ompzowe/files-api:2.0.0-ubuntu.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/files-api:2.0.0-ubuntu.v2-x-master-linux-s390x

jobs-api: (not final yet)
zowe-docker-snapshot.jfrog.io/ompzowe/jobs-api:2.0.0-ubi.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/jobs-api:2.0.0-ubi.v2-x-master-linux-s390x
zowe-docker-snapshot.jfrog.io/ompzowe/jobs-api:2.0.0-ubuntu.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/jobs-api:2.0.0-ubuntu.v2-x-master-linux-s390x

explorer-ip: (not final yet)
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-ip:2.0.0-ubi.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-ip:2.0.0-ubi.v2-x-master-linux-s390x
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-ip:2.0.0-ubuntu.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-ip:2.0.0-ubuntu.v2-x-master-linux-s390x

explorer-jes: (not final yet)
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-jes:2.0.0-ubi.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-jes:2.0.0-ubi.v2-x-master-linux-s390x
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-jes:2.0.0-ubuntu.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-jes:2.0.0-ubuntu.v2-x-master-linux-s390x

explorer-mvs: (not final yet)
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-mvs:2.0.0-ubi.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-mvs:2.0.0-ubi.v2-x-master-linux-s390x
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-mvs:2.0.0-ubuntu.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-mvs:2.0.0-ubuntu.v2-x-master-linux-s390x

explorer-uss: (not final yet)
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-uss:2.0.0-ubi.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-uss:2.0.0-ubi.v2-x-master-linux-s390x
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-uss:2.0.0-ubuntu.v2-x-master-linux-amd64
zowe-docker-snapshot.jfrog.io/ompzowe/explorer-uss:2.0.0-ubuntu.v2-x-master-linux-s390x

Base images:
base:
zowe-docker-release.jfrog.io/ompzowe/base:2.0-ubi-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/base:2.0-ubi-linux-s390x
zowe-docker-release.jfrog.io/ompzowe/base:2.0-ubuntu-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/base:2.0-ubuntu-linux-s390x

base-jdk:
zowe-docker-release.jfrog.io/ompzowe/base-jdk:2.0-ubi-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/base-jdk:2.0-ubi-linux-s390x
zowe-docker-release.jfrog.io/ompzowe/base-jdk:2.0-ubuntu-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/base-jdk:2.0-ubuntu-linux-s390x

base-node:
zowe-docker-release.jfrog.io/ompzowe/base-node:2.0-ubi-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/base-node:2.0-ubi-linux-s390x
zowe-docker-release.jfrog.io/ompzowe/base-node:2.0-ubuntu-linux-amd64
zowe-docker-release.jfrog.io/ompzowe/base-node:2.0-ubuntu-linux-s390x

**Comment by zacburns** [comment]
These have been uploaded.
