### ISSUE TITLE
Typo in pull instructions for cAdvisor

### ISSUE THREAD

**Issue by gunaly** [IBM/ibm-z-oss-hub#35]
On the pull command of the cAdvisor Docker image instructions documented here in icr.io:

https://ibm.github.io/ibm-z-oss-hub/containers/cadvisor.html

Note that it says c**A**dvisor in the pull command ("A" capitalized), but that gives an error (should be cadvisor for the pull command to work):
$ docker pull icr.io/ibmz/cAdvisor@sha256:7dac1e929b8abaaac7371b6a63c7af2ae5a5a650399d1fc49805966b0a1b5788
invalid reference format: repository name must be lowercase

This one works:
$ docker pull icr.io/ibmz/cadvisor@sha256:7dac1e929b8abaaac7371b6a63c7af2ae5a5a650399d1fc49805966b0a1b5788
icr.io/ibmz/cadvisor@sha256:7dac1e929b8abaaac7371b6a63c7af2ae5a5a650399d1fc49805966b0a1b5788: Pulling from ibmz/cadvisor
11618d768e71: Pull complete
4363f01de38a: Pull complete
7036a1407765: Pull complete
Digest: sha256:7dac1e929b8abaaac7371b6a63c7af2ae5a5a650399d1fc49805966b0a1b5788
Status: Downloaded newer image for icr.io/ibmz/cadvisor@sha256:7dac1e929b8abaaac7371b6a63c7af2ae5a5a650399d1fc49805966b0a1b5788
icr.io/ibmz/cadvisor@sha256:7dac1e929b8abaaac7371b6a63c7af2ae5a5a650399d1fc49805966b0a1b57

Note that the typo exists for all three versions: 0.42.0, 0.39.3, and 0.37.5

**Comment by zacburns** [comment]
The base template has been updated to replace the camel-case it should now be correctly listed here:

https://ibm.github.io/ibm-z-oss-hub/containers/cadvisor.html
