### ISSUE TITLE
Ansible for IBM Z image

### ISSUE THREAD

**Issue by pglopezdev** [IBM/ibm-z-oss-hub#38]
Hello,

Would it be possible to create an Ansible s390x image on the IBM Z CR? The one on dockerhub is likely a bit stale having not been updated in 3 years: https://hub.docker.com/r/ibmcom/ansible-s390x/tags

Thank you!
Phil

**Comment by korpx-z** [comment]
Hey Phil,

Ansible (version 2.13.0) is currently in the pipeline and should be made public in the coming days. At that time, I will attach a link to this image's landing page here before closing the issue.

**Comment by DebasishBlockchain** [comment]
To create an updated Ansible s390x image on the IBM Z Container Registry (IBM Z CR), you can follow these general steps:

1. **Create a Dockerfile:**

   Create a Dockerfile for Ansible that is suitable for IBM Z architecture (s390x). You can start with an existing Ansible Dockerfile and adapt it for s390x. For example:

   ```Dockerfile
   # Use a base image suitable for s390x architecture
   FROM s390x/ubuntu:20.04

   # Update and install necessary packages
   RUN apt-get update && \
       apt-get install -y software-properties-common && \
       apt-add-repository --yes --update ppa:ansible/ansible && \
       apt-get install -y ansible

   # Cleanup
   RUN apt-get clean && \
       rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

   # Set the entry point or other configurations if needed
   # ENTRYPOINT [ "ansible-playbook" ]
   ```

2. **Build the Docker Image:**

   Build the Docker image using the Dockerfile you created:

   ```bash
   docker build -t ansible-s390x:latest .
   ```

3. **Login to IBM Z Container Registry:**

   You'll need to log in to the IBM Z Container Registry with your IBM Z CR credentials:

   ```bash
   docker login <IBM_Z_CR_REGISTRY_URL>
   ```

4. **Tag and Push the Image:**

   Tag the Docker image with the IBM Z CR registry URL and then push it to the registry:

   ```bash
   docker tag ansible-s390x:latest <IBM_Z_CR_REGISTRY_URL>/ansible-s390x:latest
   docker push <IBM_Z_CR_REGISTRY_URL>/ansible-s390x:latest
   ```

   Replace `<IBM_Z_CR_REGISTRY_URL>` with the actual URL of the IBM Z CR registry where you have permission to push images.

5. **Verify the Push:**

   After successfully pushing the image to IBM Z CR, you can verify its presence by accessing the registry URL or checking it with Docker commands.

6. **Update Documentation:**

   If you're contributing this image for public use, make sure to update documentation and README files to include instructions for pulling and using the updated Ansible s390x image from the IBM Z CR.

By following these steps, you can create and publish an updated Ansible s390x image on the IBM Z Container Registry, ensuring that users have access to a more recent and reliable version of Ansible for IBM Z architecture.

**Comment by korpx-z** [comment]
This is resolved - though long overdue! (sorry!)
I assure you that these requests will be answered in a timely-manner going onward.

Thank you @DebasishBlockchain for looking into this. I referenced your instructions during my work, and though our approach was a bit different - your work proved helpful!

icr now stores image icr.io/ibmz/ansible:2.15.1-python3.10
please use our official index to navigate to the ansible landing page and copy an appropriate pull-string.
