### ISSUE TITLE
Add InfluxDB container image

### ISSUE THREAD

**Issue by rvdheij** [IBM/ibm-z-oss-hub#39]
InfluxDB is a time-series database that is frequently found in Grafana configurations for metrics storage. https://github.com/influxdata/influxdb

At least their 1.8.9 release built without problems on s390x and works well. When you aim for v2, please also include v1 since v2 is aimed at cloud-native deployment and is not compatible with the v1 product (requires migration of data and code).

**Comment by korpx-z** [comment]
Hey @rvdheij , I'm happy to inform you these images are in the pipeline, and should be public very soon (both versions 1.9.7 and 2+. I will attach a link to the corresponding web page once it's made public, and will then close this issue.

**Comment by rvdheij** [comment]
Hi @korpx-z - what's holding things up? Anything I can do (can provide Dockerfile for both, if needed)

**Comment by korpx-z** [comment]
Hey @rvdheij - sorry about the wait! This image was in our build pipeline for some time and I did not mean to leave this issue unaddressed.. we just uploaded two lightweight builds for influxdb (versions 1.9.7 and 2.2.0), you can find the newly added pages via the index.
If you have any other image requests feel free to make another issue, I'll make sure they are answered/fulfilled in a timely manner.

Again, apologies for the wait!
