### ISSUE TITLE
Include filebeat image for zCX

### ISSUE THREAD

**Issue by ahil5** [IBM/ibm-z-oss-hub#45]
Filebeat is a lightweight shipper for forwarding and centralizing log data. Installed as an agent on the server and monitors the log files or locations that you specify, collects log events, and forwards them either to Elasticsearch or Logstash.

This is needed to prototype an application running on zCX leveraging the agent.  

A guide on how to build beats binary package for Linux on IBM Z:
https://github.com/linux-on-ibm-z/docs/wiki/Building-Beats

Here is the Dockerfile recipe on how to build the beats container images:
https://github.com/linux-on-ibm-z/dockerfile-examples/blob/master/Beats/Dockerfile

Thanks
Ahilan Rajadeva

**Comment by YBA-IBM** [comment]
Image is available at 
http://icr.io/ibmz/filebeat:8.3.2
