### ISSUE TITLE
Add Signalilo container image for zCX

### ISSUE THREAD

**Issue by ahil5** [IBM/ibm-z-oss-hub#46]
Add Signalilo container image for zCX.  Signalilo is an Alertmanager to Icinga2 bridge implementation.  Signalilo acts on webhooks which it receives from Alertmanager and forwards the alerts in those webhooks.

Github source:
https://github.com/vshn/signalilo

Docker hub image for amd64:
https://hub.docker.com/r/vshn/signalilo

Thanks
Ahilan Rajadeva

**Comment by korpx-z** [comment]
Delivered directly!
(Feel free to contact me here or directly if any issues arise)
