### ISSUE TITLE
Image Request: Rasa version 3.x

### ISSUE THREAD

**Issue by jbostian** [IBM/ibm-z-oss-hub#48]
**Software Name**
The name of the software that should be considered:  Rasa

**Software Version**
The specific version(s) of the software to be included.  3.x

**Software Value**
What value does this software bring to the ecosystem (Please do not list specific customer names)
Rasa is an open source machine learning framework to automate text-and voice-based conversations.  With Rasa, you can build contextual assistants for several social media streams.

**Requestors Role**
What assets will the requester provide (Dockerfile, build files, etc...). Will the reqestor be able to update these resources as new versions are released.   
- https://github.com/RasaHQ/rasa
- https://hub.docker.com/r/rasa/rasa

**Please Note**
Requests made to this repo do not guarantee eventual inclusion in ICR. Each image will be evaluated for value, ease of currency and security concerns before a final decision is made.

**Comment by korpx-z** [comment]
Delivered directly to requester - marking this issue as closed.
