### ISSUE TITLE
Minor Type on Main Page

### ISSUE THREAD

**Issue by pglopezdev** [IBM/ibm-z-oss-hub#52]
Just a minor type on the main page:
> The hash for each container image is published. This enables users to avoid installing an **inintended** image version.

I believe this is meant to say "unintended image version."

https://github.com/IBM/ibm-z-oss-hub/blob/5b5c21e7e2701b16b3ed8e951ab0810c2c2171bb/main/main.html#L531

**Comment by zacburns** [comment]
This issue should be resolved now.
