### ISSUE TITLE
Image Request: Upgrade Grafana

### ISSUE THREAD

**Issue by rvdheij** [IBM/ibm-z-oss-hub#57]
**Software Name**
Grafana

**Software Version**
Grafana-9.0 or later

**Software Value**
Grafana-8.2 is already in the ICR, just a bit dated by now. Development in Grafana is pretty active, and new features are added frequently.

**Requestors Role**
The build for s390x failed with versions later than 8.2.3 or so due to a problem in yarn and a build dependency on a package that is not available for s390x. We've worked around the issues, and I can provide the Docker file that builds 9.0.2 to 9.0.6, and even the 9.1.0-beta1 without further change.

**Comment by rvdheij** [comment]
I'm even more confident than before, now that my Dockerfile built the 9.1.0 as well as 9.1.1 without any further change. That part might very well fit in your build process to create images without much effort.

**Comment by jabostian** [comment]
Additional client interest in this:

_The new version of node-exporter has new variable names that the supplied zCX dashboard on the Grafana website does not reference._

**Comment by rvdheij** [comment]
> Additional client interest in this:
> 
> _The new version of node-exporter has new variable names that the supplied zCX dashboard on the Grafana website does not reference._
> 
> They are requesting a new Grafana version.

I am confused. The sample dashboard 11855 on grafana.com is based off a very ancient Grafana 4 version. but appears to import nicely in Grafana 9 as well (though I have no Prometheus metrics to populate the panels). That sample dashboard is not part of the Grafana image; any enhancements would be in a new version of that sample dashboard.

PS And I'm happy to see my build process also did the latest 9.1.5 release.

**Comment by rvdheij** [comment]
I'm happy we have the Grafana 9 in the repository now, and it looks like the build issues are under control. Thank you.
