### ISSUE TITLE
Update usage notes for Jupyter notebook.

### ISSUE THREAD

**Issue by jbostian** [IBM/ibm-z-oss-hub#80]
**Image Name and Version**
Jupyter Notebook image - all versions

**Describe the bug**
Edward McCarthy discovered that our default usage notes on the web page don't result in a server that can be reached from outside the container.  Please see his description below

**To Reproduce**
Web page for Jupyter Notebook has usage notes with this example
```docker run --rm -it -p 8888:8888 icr.io/ibmz/jupyter-notebook:6.4.5```

but if use that - you cannot connect to the jupyter container from anything outside the container

but if use
```docker run --rm -d -p 8888:8888 icr.io/ibmz/jupyter-notebook:6.4.5 --ip=0.0.0.0```

adding that -ip... on the end, can then connect from a browser

also - if you just use the above cmd - can connect from browser - but only get a blank page displayed
page tried to load
...:8888/static/notebook/bundle.js

but fails - as seems jupyter in container cannot find that file

which may be because have not done any jupyter config set up , but link gives impression that if user does the run cmd they will access a ready to go jupyter env - which doesn't seem to be the case

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by korpx-z** [comment]
Ah this makes sense as 0.0.0.0 is used in-place of localhost on zcx. I'll adjust the instructions - then close this issue

**Comment by korpx-z** [comment]
usage notes have been updated! (closing this issue)
