### ISSUE TITLE
Image Request: Grafana 9.3.2

### ISSUE THREAD

**Issue by Herzog65** [IBM/ibm-z-oss-hub#82]
**Software Name**
Grafana

**Software Version**
9.3.2

**Software Value**
customer needs it 

**Requestors Role**
Just requestor

**Please Note**
Requests made to this repo do not guarantee eventual inclusion in ICR. Each image will be evaluated for value, ease of currency and security concerns before a final decision is made.

**Comment by korpx-z** [comment]
Apologies for missing this issue - it must have been assumed that updating to `9.5.1` sufficed for your needs.
I am closing this issue under the same assumption, but please do not hesitate to reopen this or let me know that this particular version is a hard requirement. If so, we will gladly create an image for you asap!
