### ISSUE TITLE
Question regarding Vulnerability Report of images in IBM Z and LinuxONE Container Registry

### ISSUE THREAD

**Issue by hem2023** [IBM/ibm-z-oss-hub#86]
If I select the Vulnerability Report, for example for Grafana 9.1.1, I get a webpage (see attachment) on cloud.ibm.com with the vulnerabilities for this package. Under overview it's status is "Do not deploy" and there are 9 vulnerabilities. How must I interpret this report?
Is it safe/wise to install/use this image? Or why has IBM not updated this image, so there are no vulnerabilities in it?
We are using this Registry for images which we want to run on our zCX instances, because we don't want to download from Docker Hub. But now I get the impression that we are still ending up with insecure images?

![Grafana](https://user-images.githubusercontent.com/128678272/227129815-def86e1d-5045-4076-b6aa-d89d18238bf2.PNG)

**Comment by korpx-z** [comment]
I'm sorry this went unattended! 
We now currently have cve resolution in place - and issues like this will be acted upon much faster in the future. I have included an image here of grafana's current standing for reference:
<img width="1384" alt="Screenshot 2023-10-18 at 4 04 18 PM" src="https://github.com/IBM/ibm-z-oss-hub/assets/72992136/4659e872-8564-4733-98a0-4cd351e7e9f9">
