### ISSUE TITLE
New image request:  Rust

### ISSUE THREAD

**Issue by pbishop62** [IBM/ibm-z-oss-hub#90]
Hi IBM,

Can there be an image provided for Rust, please?  Preferably 1.69 if possible.

I'd like to try it under zCX when (if) the image is available.  For now I'm stuck on x86 but would love to share this with Z customers and prospects.

Kind regards,
Peter

**Comment by v1gnesh** [comment]
Hi Peter,

Although I'm not IBM, you'll find that you can use a bare-bones OS container image, then use the s390x download from here - https://forge.rust-lang.org/infra/other-installation-methods.html#standalone-installers

**Comment by pbishop62** [comment]
Thanks, very handy to know.  I'll give that a shot ASAP and see how it goes.

Much obliged!

**Comment by jbostian** [comment]
Hi Everyone, we're looking Rust in a container for Linux and z/OS (zCX), because there has been significant interest in it.  It's a work-in-progress, and don't have any thing to post yet, but it's on our radar.  We'll let everyone know when something is available.

**Comment by pbishop62** [comment]
Thanks Joe, I'll see how I go with the zCX installation in the meantime.  Might take a week or so to get everything sorted out.

Best regards,
Peter

**Comment by pbishop62** [comment]
Hmmm...I tried ubuntu and alpine in zCX, neither of which had curl, and finally installed Almalinux in zCX which does have curl, and got Rust installed using the standalone installer for s390x from the link shared by v1gnesh above, but then the "cargo run" failed due to there not being a linker (it was looking for 'cc').  

I'll keep looking for a proper Linux distro that will run on s390x, but if anyone has a suggestion I'm all ears, as I'd really like to try Rust in zCX.

**Comment by v1gnesh** [comment]
cc refers to a C compiler. Try installing dev tools into the OS you're using. Package name(s) will vary based on distro.

**Comment by pbishop62** [comment]
Thanks v1gnesh.  I'll dig around the AlmaLinux site and see if I can find the right package.

Much obliged!
Peter

**Comment by pbishop62** [comment]
Update - I now have Rust running on zCX after "yum install gcc" on my AlmaLinux container.

Yay!

Thanks to v1gnesh for the pointers.

Off to go and start some Rust experimentation,
Peter

**Comment by korpx-z** [comment]
Just uploaded version 1.73.0 of rust (based in ubuntu:22.04).
Please reference our web-index to find the official hash/pull-string for image `icr.io/ibmz/rust:1.73.0-jammy`

I hope it proves useful to you and others - if there are any issues please feel free to reopen this ticket and let me know!
(issues like these will be answered & resolved at a much quicker rate going onward btw)
