### ISSUE TITLE
Image Request: Fluent-Bit for s390x

### ISSUE THREAD

**Issue by ahil5** [IBM/ibm-z-oss-hub#93]
**Software Name**
fluent-bit

**Software Version**
2.1.8

**Software Value**
Fluent Bit is an open-source, pluggable, lightweight log collector and forwarder.
Becoming a preferred option in Kubernetes/OpenShift containerized environments.

How to build and install:
https://docs.fluentbit.io/manual/installation/sources/build-and-install

Available Docker images:
https://docs.fluentbit.io/manual/installation/docker
Note:  s390x is currently not available

How to build Docker images (for x86 arch):
https://github.com/fluent/fluent-bit-docker-image/blob/master/Dockerfile.x86_64

**Requestors Role**
Will self-support

**Please Note**
Requests made to this repo do not guarantee eventual inclusion in ICR. Each image will be evaluated for value, ease of currency and security concerns before a final decision is made.

**Comment by korpx-z** [comment]
fluent-bit has been added :)
